name: Deploy to Cloudways

on:
  push:
    branches:
      - staging
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging
        if: github.ref_name == 'staging'
        run: |
          curl -s "https://wordpress-1358704-4998730.cloudwaysapps.com/gitautodeploy.php?server_id=1358704&app_id=4998730&git_url=git@github.com:Stevebeans/bbj-2025.git&branch_name=staging"
          echo "Triggered staging deployment"

      - name: Deploy to Production
        if: github.ref_name == 'master'
        run: |
          curl -s "https://${{ secrets.LIVE_DOMAIN }}/gitautodeploy.php?server_id=1358704&app_id=${{ secrets.LIVE_APP_ID }}&git_url=git@github.com:Stevebeans/bbj-2025.git&branch_name=master"
          echo "Triggered production deployment"
